{
 "title": "Bobcares - MAIN dashboard",
 "description": "DO NOT DELETE\nThis is a dashboard for your Kubernetes cluster(s). \nMade for kube-prometheus-stack and take advantage of the latest Grafana features.",
 "tags": [
  "Kubernetes",
  "Prometheus",
  "DO NOT DELETE"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_node_info,cluster)"
    }
   },
   { "name": "resolution", "query": "1s, 15s, 30s, 1m, 3m, 5m" },
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_info{cluster=\"$cluster\"}, node)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(node_uname_info{nodename=~\"(?i:($node))\"},instance)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$cluster\"},namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"$namespace\", cluster=\"$cluster\"},pod)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"$Namespace\", cluster=\"$cluster\"},job)"
    }
   },
   {
    "name": "coreDNSjob",
    "query": {
     "query": "label_values(coredns_build_info{cluster=\"$cluster\"},job)"
    }
   },
   {
    "name": "corednsinstance",
    "query": {
     "query": "label_values(up{job=\"$coreDNSjob\", cluster=\"$cluster\"},instance)"
    }
   },
   {
    "name": "protocol",
    "query": {
     "query": "label_values(coredns_dns_requests_total{cluster=\"$cluster\"},proto)"
    }
   },
   {
    "name": "job1",
    "query": {
     "query": "label_values(node_cpu_seconds_total,job)"
    }
   },
   {
    "name": "created_by",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"$namespace\", cluster=\"$cluster\"},created_by_name)"
    }
   },
   {
    "name": "server",
    "query": {
     "query": "label_values(node_boot_time_seconds,server)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    { "title": "Global CPU  Usage", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 65 } },
    { "title": "Global RAM Usage", "gridPos": { "h": 5, "w": 6, "x": 6, "y": 65 } },
    { "title": "Kubernetes Resource Count", "gridPos": { "h": 9, "w": 12, "x": 12, "y": 65 } },
    { "title": "CPU Usage", "gridPos": { "h": 4, "w": 6, "x": 0, "y": 70 } },
    { "title": "RAM Usage", "gridPos": { "h": 4, "w": 6, "x": 6, "y": 70 } },
    { "title": "All processes memory usage", "gridPos": { "h": 9, "w": 24, "x": 0, "y": 74 } },
    {
     "title": "All processes CPU usage (1m avg)",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 83 }
    },
    {
     "title": "File Descriptors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
     "targets": [
      {
       "expr": "node_filefd_maximum{instance=\"$instance\", cluster=\"$cluster\"}",
       "legendFormat": "Maximum file descriptors"
      },
      {
       "expr": "node_filefd_allocated{instance=\"$instance\", cluster=\"$cluster\"}",
       "legendFormat": "Allocated file descriptors"
      }
     ]
    },
    {
     "title": "Context Switches & Interrupts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
     "targets": [
      {
       "expr": "rate(node_context_switches_total{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "Context switches"
      },
      {
       "expr": "rate(node_intr_total{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "Interrupts"
      }
     ]
    },
    {
     "title": "System Load",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
     "targets": [
      {
       "expr": "node_load1{instance=\"$instance\", cluster=\"$cluster\"}",
       "legendFormat": "1m"
      },
      {
       "expr": "node_load5{instance=\"$instance\", cluster=\"$cluster\"}",
       "legendFormat": "5m"
      },
      {
       "expr": "node_load15{instance=\"$instance\", cluster=\"$cluster\"}",
       "legendFormat": "15m"
      }
     ]
    },
    {
     "title": "Time Sync",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "node_timex_estimated_error_seconds{instance=\"$instance\", cluster=\"$cluster\"}",
       "legendFormat": "Estimated error in seconds"
      },
      {
       "expr": "node_timex_maxerror_seconds{instance=\"$instance\", cluster=\"$cluster\"}",
       "legendFormat": "Maximum error in seconds"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "All processes network I/O (1m avg)",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 66 }
    },
    {
     "title": "Network usage (bytes)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(node_network_receive_bytes_total{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "In"
      },
      {
       "expr": "- sum(rate(node_network_transmit_bytes_total{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "Network total drops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(node_network_receive_drop_total{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "In"
      },
      {
       "expr": "- sum(rate(node_network_transmit_drop_total{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "Network usage (packet/s)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(node_network_receive_packets_total{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "In"
      },
      {
       "expr": "- sum(rate(node_network_transmit_packets_total{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "NF Conntrack",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_nf_conntrack_entries{instance=\"$instance\", cluster=\"$cluster\"}",
       "legendFormat": "NF Conntrack entries"
      },
      {
       "expr": "node_nf_conntrack_entries_limit{instance=\"$instance\", cluster=\"$cluster\"}",
       "legendFormat": "NF Conntrack limit"
      }
     ]
    },
    { "title": "Network - Packets Rate", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 } },
    { "title": "Network - Bandwidth", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 } },
    {
     "title": "TCP Currently Established",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab{instance=\"$instance\", cluster=\"$cluster\"}",
       "legendFormat": "TCP Currently Established"
      }
     ]
    },
    {
     "title": "Network errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(node_network_receive_errs_total{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "In"
      },
      {
       "expr": "- sum(rate(node_network_transmit_errs_total{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Out"
      }
     ]
    },
    { "title": "Network I/O pressure", "gridPos": { "h": 6, "w": 24, "x": 0, "y": 110 } }
   ]
  },
  {
   "title": "Persistant Volumes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    { "title": "Persistent volumes", "gridPos": { "h": 4, "w": 4, "x": 0, "y": 67 } },
    {
     "title": "Persistent volumes bytes requested",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 67 }
    },
    { "title": "Bound persistent volumes", "gridPos": { "h": 4, "w": 4, "x": 8, "y": 67 } },
    { "title": "Unbound persistent volumes", "gridPos": { "h": 4, "w": 4, "x": 12, "y": 67 } },
    { "title": "Failed persistent volumes", "gridPos": { "h": 4, "w": 4, "x": 16, "y": 67 } },
    { "title": "Pending persistent volumes", "gridPos": { "h": 4, "w": 4, "x": 20, "y": 67 } }
   ]
  },
  {
   "title": "CoreDNS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    { "title": "CoreDNS - Health Status", "gridPos": { "h": 6, "w": 24, "x": 0, "y": 68 } },
    {
     "title": "CoreDNS - Memory Usage by instance",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 }
    },
    {
     "title": "CoreDNS - CPU Usage by instance",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 }
    },
    {
     "title": "CoreDNS - Average Packet Size  ($protocol)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 }
    },
    {
     "title": "CoreDNS - Requests by return code",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 }
    },
    { "title": "CoreDNS - Requests by type", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 } },
    {
     "title": "CoreDNS - Total DNS Requests ($protocol)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 }
    }
   ]
  },
  {
   "title": "Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    { "title": "Cluster filesystem usage", "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 } },
    { "title": "Cluster CPU usage (1m avg)", "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 } },
    { "title": "Cluster memory usage", "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 } },
    { "title": "Used", "gridPos": { "h": 3, "w": 4, "x": 0, "y": 12 } },
    { "title": "Total", "gridPos": { "h": 3, "w": 4, "x": 4, "y": 12 } },
    { "title": "Used", "gridPos": { "h": 3, "w": 4, "x": 8, "y": 12 } },
    { "title": "Total", "gridPos": { "h": 3, "w": 4, "x": 12, "y": 12 } },
    { "title": "Memory Total", "gridPos": { "h": 3, "w": 4, "x": 16, "y": 12 } },
    { "title": "Used", "gridPos": { "h": 3, "w": 4, "x": 20, "y": 12 } },
    { "title": "Cluster Memory Requests", "gridPos": { "h": 3, "w": 6, "x": 0, "y": 15 } },
    { "title": "Nodes Filesystem Usage", "gridPos": { "h": 3, "w": 6, "x": 6, "y": 15 } },
    { "title": "Cluster CPU Requests", "gridPos": { "h": 3, "w": 6, "x": 12, "y": 15 } },
    { "title": "POD Usage", "gridPos": { "h": 3, "w": 6, "x": 18, "y": 15 } },
    { "title": "Cluster Memory Utilization", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 } },
    { "title": "Cluster CPU Utilization", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 } },
    {
     "title": "Memory Utilization by namespace",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 }
    },
    { "title": "CPU Utilization by namespace", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 } },
    {
     "title": "Namespace(s) usage on total cluster CPU in %",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 }
    },
    {
     "title": "Namespace(s) usage on total cluster RAM in %",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 }
    },
    { "title": "Failures", "gridPos": { "h": 8, "w": 9, "x": 0, "y": 41 } },
    { "title": "Failures", "gridPos": { "h": 4, "w": 3, "x": 9, "y": 41 } },
    { "title": "Workload", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 } },
    { "title": "Alerts", "gridPos": { "h": 4, "w": 3, "x": 9, "y": 45 } }
   ]
  },
  {
   "title": "Node Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "FS usage in %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$instance\", cluster=\"$cluster\"} * 100) / node_filesystem_size_bytes{instance=\"$instance\", cluster=\"$cluster\"})",
       "legendFormat": "{{ mountpoint }}"
      }
     ]
    },
    {
     "title": "FS inode usage in %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (node_filesystem_files_free{instance=\"$instance\", cluster=\"$cluster\"} / node_filesystem_files{instance=\"$instance\", cluster=\"$cluster\"} * 100)",
       "legendFormat": "{{ mountpoint }}"
      }
     ]
    },
    {
     "title": "Reads by disk (bytes)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(node_disk_read_bytes_total{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Writes by disk (bytes)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(node_disk_written_bytes_total{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Completed reads by disk",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "read/s" } },
     "targets": [
      {
       "expr": "rate(node_disk_reads_completed_total{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Completed writes by disk",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "write/s" } },
     "targets": [
      {
       "expr": "rate(node_disk_writes_completed_total{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk(s) io/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "io/s" } },
     "targets": [
      {
       "expr": "rate(node_disk_io_now{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval]) ",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "FS - Device Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(node_filesystem_device_error{instance=\"$instance\", cluster=\"$cluster\"}) by (mountpoint)",
       "legendFormat": "{{ mountpoint }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    { "title": "Nodes", "gridPos": { "h": 3, "w": 3, "x": 0, "y": 70 } },
    { "title": "Nodes unavailable", "gridPos": { "h": 3, "w": 3, "x": 3, "y": 70 } },
    { "title": "Nodes w. disk pressure", "gridPos": { "h": 3, "w": 4, "x": 6, "y": 70 } },
    { "title": "Nodes w. mem pressure", "gridPos": { "h": 3, "w": 4, "x": 10, "y": 70 } },
    { "title": "Nodes unshedulable", "gridPos": { "h": 3, "w": 4, "x": 14, "y": 70 } },
    {
     "title": "Next Kubelet Certificate Expiry [days]",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 70 }
    },
    {
     "title": "CPU  Usage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(sum by (cpu) (rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\", instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RAM Usage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes{instance=\"$instance\", cluster=\"$cluster\"} - node_memory_MemAvailable_bytes{instance=\"$instance\", cluster=\"$cluster\"}) / sum(node_memory_MemTotal_bytes{instance=\"$instance\", cluster=\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Pods on node",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 73 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_info{node=\"$node\", cluster=\"$cluster\"})"
      }
     ]
    },
    {
     "title": "List of pods on node ($node)",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 73 },
     "targets": [
      {
       "expr": "kube_pod_info{node=\"$node\", cluster=\"$cluster\"}"
      }
     ]
    },
    {
     "title": "CPU Used",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\", instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "CPU Total",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 2, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(machine_cpu_cores{node=\"$node\", cluster=\"$cluster\"})"
      }
     ]
    },
    {
     "title": "RAM Used",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 4, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes{instance=\"$instance\", cluster=\"$cluster\"} - node_memory_MemAvailable_bytes{instance=\"$instance\", cluster=\"$cluster\"})"
      }
     ]
    },
    {
     "title": "RAM Total",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 6, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "machine_memory_bytes{node=\"$node\", cluster=\"$cluster\"}"
      }
     ]
    },
    {
     "title": "uptime",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_time_seconds{instance=\"$instance\", cluster=\"$cluster\"} - node_boot_time_seconds{instance=\"$instance\", cluster=\"$cluster\"}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(rate(node_cpu_seconds_total{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval]) * 100) by (mode)",
       "legendFormat": "{{ mode }}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"$instance\", cluster=\"$cluster\"} - node_memory_MemFree_bytes{instance=\"$instance\", cluster=\"$cluster\"} - (node_memory_Cached_bytes{instance=\"$instance\", cluster=\"$cluster\"} + node_memory_Buffers_bytes{instance=\"$instance\", cluster=\"$cluster\"})",
       "legendFormat": "RAM Used"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"$instance\", cluster=\"$cluster\"}",
       "legendFormat": "RAM Total"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=\"$instance\", cluster=\"$cluster\"}",
       "legendFormat": "RAM Cache"
      },
      {
       "expr": "node_memory_Buffers_bytes{instance=\"$instance\", cluster=\"$cluster\"}",
       "legendFormat": "RAM Buffer"
      },
      {
       "expr": "node_memory_MemFree_bytes{instance=\"$instance\", cluster=\"$cluster\"}",
       "legendFormat": "RAM Free"
      },
      {
       "expr": "node_memory_SwapTotal_bytes{instance=\"$instance\", cluster=\"$cluster\"} - node_memory_SwapFree_bytes{instance=\"$instance\", cluster=\"$cluster\"}",
       "legendFormat": "SWAP Used"
      },
      {
       "expr": "node_memory_SwapTotal_bytes{instance=\"$instance\", cluster=\"$cluster\"}",
       "legendFormat": "SWAP Total"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    { "title": "PODs Running", "gridPos": { "h": 3, "w": 5, "x": 0, "y": 8 } },
    { "title": "PODs Pending", "gridPos": { "h": 3, "w": 5, "x": 5, "y": 8 } },
    { "title": "PODs Succeeded", "gridPos": { "h": 3, "w": 5, "x": 10, "y": 8 } },
    { "title": "PODs Failed", "gridPos": { "h": 3, "w": 5, "x": 15, "y": 8 } },
    { "title": "PODs Status Unknown", "gridPos": { "h": 3, "w": 4, "x": 20, "y": 8 } },
    { "title": "Running on", "gridPos": { "h": 4, "w": 6, "x": 0, "y": 11 } },
    { "title": "Created by", "gridPos": { "h": 8, "w": 6, "x": 6, "y": 11 } },
    { "title": "CPU usage by Pod", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 } },
    { "title": "Pod IP", "gridPos": { "h": 4, "w": 6, "x": 0, "y": 15 } },
    { "title": "Memory usage by Pod", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 } },
    { "title": "Pods memory usage", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 } },
    { "title": "Memory Limits Ratio", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 } },
    { "title": "Memory Requests Ratio", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 } },
    { "title": "Pods CPU usage (1m avg)", "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 } },
    { "title": "Pods Running Count", "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 } }
   ]
  },
  {
   "title": "Containers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    { "title": "Containers", "gridPos": { "h": 3, "w": 6, "x": 0, "y": 9 } },
    { "title": "Container restarts [/hour]", "gridPos": { "h": 3, "w": 6, "x": 6, "y": 9 } },
    { "title": "CPU Usage by container", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 } },
    { "title": "Resources by container", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 } },
    { "title": "Memory Usage by container", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 } },
    { "title": "Container Memory Usage", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 } }
   ]
  },
  {
   "title": "API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    { "title": "API Server - Health Status", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 } },
    {
     "title": "API Server - CPU Usage by instance",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 }
    },
    {
     "title": "API Server - HTTP Requests by code",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 }
    },
    {
     "title": "API Server - Memory Usage by instance",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 }
    },
    {
     "title": "API Server - HTTP Requests Latency by instance",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 }
    },
    {
     "title": "API Server - Stacked HTTP Requests by instance",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 }
    },
    { "title": "API Server Request Rate", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 } },
    {
     "title": "API Server - HTTP Requests by verb",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 }
    },
    {
     "title": "API Server - HTTP Requests Latency by verb",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 }
    },
    {
     "title": "API Server - Work Queue by instance",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 }
    },
    { "title": "API Server - Errors by verb", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 } },
    {
     "title": "API Server - Errors by Instance",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 }
    }
   ]
  },
  {
   "title": "Prometheus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    { "title": "TSDB Head Series", "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 } },
    { "title": "Discovered Targets", "gridPos": { "h": 5, "w": 4, "x": 4, "y": 11 } },
    { "title": "Prometheus version", "gridPos": { "h": 5, "w": 4, "x": 8, "y": 11 } },
    { "title": "Liveness by pod", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 } },
    {
     "title": "TSDB Head Series & Chunks by pod",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 }
    },
    {
     "title": "Engine Query Duration by pod, slice",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 }
    },
    { "title": "Number of Targets by pod", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 } },
    {
     "title": "Config - Last Successful Reload by pod",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 }
    }
   ]
  }
 ]
}